### PR TITLE
Libstemmer upgraded to version 2.0 & 9 new stemming languages added

### PR DESCRIPTION
**Pull request by valdemaras-pipiras**
Basque, Catalan, Greek, Indonesian, Irish, Lithuanian, Nepali, Serbian and Yiddish stemming languages added

### CODE REVIEW

**Comment by emmanuelkeller** [comment]
@valdemaras-pipiras Thanks for this great contribution ! Could you sign the CLA ?

> [CLA assistant check](https://cla-assistant.io/RediSearch/RediSearch?pullRequest=1727) 
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RediSearch/RediSearch?pullRequest=1727) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RediSearch/RediSearch?pullRequest=1727) it.

**Comment by valdemaras-pipiras** [comment]
Contributor License Agreement is signed.

**Comment by valdemaras-pipiras** [comment]
I've signed CLA license. 
Are there more issues stopping to merge the PR?

**Comment by ashtul** [comment]
@valdemaras-pipiras PR #1708 Is very similar.
Just noted they have released a new version this month.

**Comment by valdemaras-pipiras** [comment]
> @valdemaras-pipiras PR #1708 Is very similar.
> Snowball had just released a new version this month.
> Can you please update the PR with this update?

It seams my PR is a bit too late.

**Pull request closed without merging**
