### PR TITLE
Issue#1193

### LINKED ISSUE #1193: FT.ADD ... REPLACE without all fields leaves unindexed fields
If you create a schema with multiple fields then later use `FT.ADD .. REPLACE` but do not specify all the indexed fields, the document will still contain the field yet it won't be present in the index. Tested with 1.4.x and 1.6.x. Note `age` below:

```
> FT.CREATE myppl SCHEMA first TEXT last TEXT age NUMERIC
OK
> FT.ADD myppl instructor 1 FIELDS first Kyle last Davis age 39 country Canada
OK
> FT.SEARCH myppl "@age:[39 39]"
1) (integer) 1
2) "instructor"
3) 1) first
   2) "Kyle"
   3) last
   4) "Davis"
   5) age
   6) "39"
   7) country
   8) "Canada"
> FT.ADD myppl instructor 1 REPLACE FIELDS first Loris last Cro
OK
> FT.GET myppl instructor
1) "first"
2) "Loris"
3) "last"
4) "Cro"
5) "age"
6) "39"
7) "country"
8) "Canada"
> FT.SEARCH myppl "@age:[39 39]"
1) (integer) 0
```

It's unusual behaviour but it seems like it's doing basically a `FT.DEL` without DD, then doing an `FT.ADD` with the specified fields only (which is makes sense since the un-indexed field `country` is also persisting).

### PR DESCRIPTION
**Pull request by ashtul**
fix #1193

What should be the behavior for REPLACE NOCREATE (w/o PARTIAL)
Current behavior to not break test but these two seem to contradict

### CODE REVIEW

**Comment by stockholmux** [comment]
Could someone be relying on the affect described in #1193? This would be a breaking change, no?

**Comment by ashtul** [comment]
@stockholmux It could be the case. @MeirShpilraien believes it is the right behavior as is. Possibly the DD option you suggest is the way to go.

**Comment by stockholmux** [comment]
@ashtul `DD` would probably be preferable over changing the existing behaviour.

**Comment by ashtul** [comment]
Should get a `DD` option.
Do not merge for now!

**Comment by MeirShpilraien** [comment]
@ashtul @gkorland @K-Jo what is the decision here? How should we call this parameter?

**Comment by ashtul** [comment]
PR is not relevant anymore.
Issue #1193 still open and in the future may get `DD` flag.

**Pull request closed without merging**
