### PR TITLE
replace int with uint32_t

### PR DESCRIPTION
**Pull request by gkorland**

### CODE REVIEW

**Comment by ashtul** [comment]
@gkorland lgtm-bot complains about two places where the number can be negative, so unit32 isn't a good match.

**Comment by gkorland** [comment]
@ashtul are right it uses -1 as "False"

**Comment by ashtul** [comment]
@gkorland  Will moving to `size_t` help the CPU to be move efficient as it will use the most natural size of the variable?

**Comment by gkorland** [comment]
Yes, some of the commands like divide are cheaper this way

**Comment by oshadmi** [comment]
@ashtul `size_t` is unsigned. Will we still need to use it for, or compare it against, negative values (-1) ? Not recommended.
Seems better to check if it is greater than `SIZE_MAX`.

**Comment by ashtul** [comment]
@oshadmi Silly me :)

**Pull request closed without merging**
