### PR TITLE
save low docID in mmh instead of high

### PR DESCRIPTION
**Pull request by ashtul**
Currently, when a new Document is found, if the sorting function, whether by field or score, returns `equal,` we pop the item with the smallest docID and replace it with the new docID, which in RS is always higher. Therefore the min-max heap works very hard.

This PR leaves in a heap the smaller docIDs and therefore saves on the time wasted otherwise.

We do not commit the order of results, so this change, while requiring fixing many tests on both the module and clients, does not represent a breaking change since there is no commitment about the order of results in cases like this.

Furthermore, in RS 2.0, after reloading from rdb, the order of documents might and probably will change, so whatever reason there could have been for this in previous versions is now gone.

Improvement of performance can be significant when there are many results. In some cases, it can be 20% or more.

### CODE REVIEW

**Comment by rafie** [comment]
@ashtul In the tests, wouldn't it be better to sort the results before comparing them to expected?

**Comment by ashtul** [comment]
> @ashtul In the tests, wouldn't it be better to sort the results before comparing them to expected?
@rafie 
It will hide changes if they occur.

**Comment by MeirShpilraien** [comment]
@ashtul did you tested on the coordinator? are the tests changes pass there?
If it does then it looks good to me.

**Comment by ashtul** [comment]
> @ashtul did you tested on the coordinator? are the tests changes pass there?
> If it does then it looks good to me.

@MeirShpilraien - Checked tests on the coordinator. There was one change required which you can see in [this commit](https://github.com/RediSearch/RediSearch/pull/1628/commits/64ca46daa5eb2595e200069f9192ea910c5dca6c). The change makes the coordinator more in-line with a single shard.

**Comment by ashtul** [comment]
@K-Jo, this change introduces a minor behavior change. If the documents' score is equal, RS will return the documents with the lower IDs rather than the higher IDs.

Currently, if the documents' score is equal, the document with the higher ID is inserted into the result-heap where top results are being stored. If a query has a million documents with the same score and 10 results should be returned, the heap will pop and insert all million results. After this change, the first 10 results will be inserted and the rest will be skipped.

The benefit will change depends on the query. In `bm_test.py`, 1000000 documents are loaded with 1 of 1000 words (so there are 1000 documents per word). A query for all documents (`*`) is called 10 times with a limit of 100 results. On my system, there is a reduction in query time from ~15 seconds to less than 5 seconds.

**Comment by ashtul** [comment]
`mmh_peek_min`, `mmh_insert` and `mmh_pop_min` are 68% of execution time.

high_id

`mmh_peek_min` requires 3% of execution time

low_id

**Comment by K-Jo** [comment]
@ashtul lets do this on the 2.2 and make sure we label this correctly for our release notes as a minor breaking change

**Review by MeirShpilraien — APPROVED** [review]

**Pull request merged**
