### PR TITLE
revert LOG_ASSERT PR.

### PR DESCRIPTION
**Pull request by ashtul**
Comes build-in with Redis 6.0

### CODE REVIEW

**Comment by ashtul** [comment]
You're right but won't it limit us to redis 6?

**Comment by ashtul** [comment]
@MeirShpilraien 
also, redis_assert doesn't allow for an additional string as we did, so this will remove clutter.

**Comment by MeirShpilraien** [comment]
@ashtul yes but you do not really need it if you have line and file, its just nice to have. Also we can implement it as RedisModule_Log with the message and call RedisModule_Assert..

**Comment by ashtul** [comment]
Will use assert + log instead

**Comment by ashtul** [comment]
replaced by #1239

**Pull request closed without merging**
