### PR TITLE
Break down commands documentation into subsections

### LINKED ISSUE #1504: Update commands page for 2.0
Attempt to add structure to RediSearch commands reference for increased adoption

Should have a table at the start like this: https://oss.redislabs.com/redisgears/commands.html
Should have categories in the table like here: https://oss.redislabs.com/redistimeseries/commands/

- Full-text Search
  - Create & populate index
     - FT.CREATE
     - HSET, ....
  - Query
     - FT.SEARCH
     - FT.AGGREGATE
     - FT.EXPLAIN ...
     - FT.TAGVALS
  - Administer
    - FT.ALTER
    - FT.DROPINDEX
    - FT.INFO
    - FT.ALIAS
- Suggestions
    - ...

### PR DESCRIPTION
**Pull request by ashtul**
fix #1504

### CODE REVIEW

**Comment by ashtul** [comment]
Documentation will look like this...

Screenshot from 2020-09-10 17-32-03
Screenshot from 2020-09-10 17-32-06

**Comment by bmansheim** [comment]
@ashtul Nice hack. Do you just want to make all of the site show only the top-level headings?

**Comment by ashtul** [comment]
@bmansheim please coordinate with @K-Jo 
Thanks

**Review by K-Jo — APPROVED** [review]

**Comment by K-Jo** [comment]
@ashtul love the branch name

**Comment by K-Jo** [comment]
Please merge to 2.0 branch as well @rafie @ashtul

**Pull request merged**
