### PR TITLE
fix -20* query

### PR DESCRIPTION
**Pull request by ashtul**
The query `FT.EXPLAIN idx -20*` which returned error `Syntax error at offset 3 near -20` now recognize `PREFIX{-20*}`

### CODE REVIEW

**Comment by ashtul** [comment]
related to #1304 & #1314

**Comment by ashtul** [comment]
@K-Jo Please check documentation

**Comment by ashtul** [comment]
fix #1304 
extra documentation

**Comment by rafie** [comment]
No changes in `parser.y`?

**Comment by ashtul** [comment]
@rafie 
removed changes to `parser.c` and added a test.

**Pull request merged**
