### PR TITLE
Unify repeated Lettuce/Spring clients and remove JRediSearch

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by gkorland** [comment]
@sazzad16 I think since JRediSearch is deprecated we should remove it

**Comment by sazzad16** [comment]
@gkorland redis-om-spring is using JRediSearch at this moment. Perhaps we can wait for some time before removing it.

**Comment by gkorland** [comment]
@sazzad16 we should remove it so new users won't start new projects with JRediSearch

**Review by ashtul — APPROVED** [review]
:+1:

**Pull request merged**
