### PR TITLE
FORK GC will now squash the invidx and will not leave empty blocks (#…

### PR DESCRIPTION
**Pull request by mnunberg**
…683)

* FORK GC will now squash the invidx and will not leave empty blocks

* fix failing tests

* fix failing test

* fix failing tests

* review fixes

* review fixes

* fix failing tests

### CODE REVIEW

**Comment by mnunberg** [comment]
Seems there are test failures here. Will inspect..

**Comment by MeirShpilraien** [comment]
@mnunberg lets not use force push next time so I will be able to see only the changes you made and not review everything from scratch

**Comment by MeirShpilraien** [comment]
In addition we need to add some tests for this to know that its actually working

**Comment by mnunberg** [comment]
Yeah, I'm uncomfortable with disabling the tests too. Should we enable them back?

**Comment by MeirShpilraien** [comment]
@mnunberg I think we should enable them back but we need to do some modification because now (unlike default GC) the fork gc will not clean the last block n the inverted index. We need to adjust the tests to add 100 docs so we will have 2 blocks in the inverted indexes and then we can check that the fork GC cleans it.

**Comment by mnunberg** [comment]
@MeirShpilraien Can you adjust the tests?

**Pull request merged**
