### PR TITLE
feat: Add hindi snowball stemmer

### PR DESCRIPTION
**Pull request by joeirimpan**

### CODE REVIEW

**Comment by mnunberg** [comment]
@joeirimpan can you sign the CLA? looks good otherwise!

**Comment by joeirimpan** [comment]
@mnunberg signed

**Comment by mnunberg** [comment]
Can you add a basic test (in https://github.com/RediSearch/RediSearch/blob/master/src/pytest/test.py)just to ensure that this feature works?

**Comment by mnunberg** [comment]
Thanks!

**Pull request merged**
