### PR TITLE
WIP: First rust code

### PR DESCRIPTION
**Pull request by MeirShpilraien**
The following PR is the first step in long processes of moving RediSearch components into rust. Rust gives us a better safety guarantees in term of memory violation such as segfault and leaks.

The PR chooses one of the simplest components of RediSearch, the trie, and re implement it in rust. RediSearch can use this new implementation using C API that the rust code exposes. The C API tries to be as close as possible to the original C trie implementation so we can avoid massive code changes to the C code that uses this trie. In addition, the implementation itself tries to be as close as possible to the C implementation to make sure the performance and memory usage will be as close as possible.

The PR also put the grounds to add more rust components in the future. The PR introduce a new code directory under `src` directory called `redisearch_rs`. This directory is a rust workspace project. All the rust crates that will be created in the future will be added to this directory. The build system compiled this rust code by invoking `cargo build` inside `redisearch_rs` directory which will build the rust code and create static libraries (`.a` files) that the C code can statically link to.

Whenever we replace an existing unit with a rust implementation we should make sure we check the following:
* Performance
* Memory usage
* Binary size

## Low Level Details

The trie implementation replaces the C trie_map implementation that was located under `deps/trie_map` this trie map was used all over in different places. All usage of this trie map was replace with the rust implementation. **Notice** that this is not the only trie implementation that we have on RediSearch. We also have trie implementation under `src/trie` that is used for the terms trie  and also contains extra logic for LD. A follow up PR will attempt to replace this other trie with rust trie and finally merge that 2 tries implementations.

The current rust trie is used on:
1. Tag fields
2. Stop words
3. Extensions API (extenders and scorers)
4. Coordinator

### Trie Memory Consumption

The current C trie implementation uses tricks to improve the trie memory usage. Those tricks causes unaligned memory access which is considered undefined behaviour. The rust implementation do not perform such tricks and so consume more memory. From benchmark we can see that the total memory usage was increased by around 4%, we believe this is acceptable.

Please  notice that though the rust implementation does not perform tricks that cause unaligned memory access, it does try to improve memory usage with "legal" techniques such as:

1. Using a costume vector implementation that can hold up to 4G elements at the cost of improve the memory usage compare to rust vector implementation. This costume vector is used all over the trie include holding the children array and the current node value. This means that the node value can be up to 4G long, we believe this is more then enough and there is not need to implement fallback logic if such thing happened (notice that the C implementation assume that node value can be up to 65536 bytes long and also do not implement any fallback logic).

2. Holding the children array inside `Option<Box<...>>`. This technique allows us to consume a single byte in case the children array is empty. This is respectively common because all the leaves has an empty children array.

### Benchmark Wildcard and Contains

On the current benchmark that we have, no regressions was observed.

**Notice** that currently we have not benchmark for TAG fields. This means that the benchmark are not really cover the cases of wildcard and contains. We should add such benchmark as a followup PR and see if there is any regressions.

### Bug fixes

* Fix bug where lex range with the same max and min was not case insensitive.

## Followup PR's

1. Benchmark for tags fields including:
   * Wildcard
   * Contains
   * Lex range
2. Replace the other trie implementation with the rust trie.

Todo:
- [x] Move all the usages of the trie to use the rust implementation.
- [x] Implements missing functionalities such as pattern and wildcard search.
- [ ] Support timeout on trie iterator
- [x] Improve rust testings.
- [x] Test for performance regressions.
- [x] Test for memory usage regressions - memory seems to increase by around 4%, see section about memory usage.
- [ ] Consult with @rafie on the best way to add it to the build system.

### CODE REVIEW

**Comment by filipecosta90** [comment]
### Automated performance analysis summary

This comment was automatically generated given there is performance data available.

In summary:
- Detected a total of 14 stable tests between versions.
- Detected a total of 2 highly unstable benchmarks.
- Detected a total of 3 regressions bellow the regression water line 5.0.

You can check a comparison in detail via the [grafana link](https://benchmarksrediscom.grafana.net/d//3Ejv2wZnk/?var-branch=master&var-branch=first_rust_code)

### Comparison between master and first_rust_code.

Time Period from 30 days ago. (environment used: oss-standalone)

|                           Test Case                            |Baseline master (median obs. +- std.dev)|Comparison first_rust_code (median obs. +- std.dev)|% change (higher-better)|             Note              |
|----------------------------------------------------------------|----------------------------------------|---------------------------------------------------|------------------------|-------------------------------|
|ftsb-10K-enwiki_abstract-hashes-term-prefix                     | 7739 +- 3.4%  (7 datapoints)           | 7766 +- nan%  (1 datapoints)                      |0.3%                    |-- no change --                |
|ftsb-10K-enwiki_abstract-hashes-term-suffix                     | 1847 +- 0.5%  (7 datapoints)           | 1848 +- nan%  (1 datapoints)                      |0.0%                    |-- no change --                |
|ftsb-10K-enwiki_abstract-hashes-term-suffix-withsuffixtrie      | 80954 +- 5.2%  (7 datapoints)          | 82201 +- nan%  (1 datapoints)                     |1.5%                    |waterline=5.2%. -- no change --|
|ftsb-10K-enwiki_abstract-hashes-term-wildcard                   | 12795 +- 4.2%  (7 datapoints)          | 13272 +- nan%  (1 datapoints)                     |3.7%                    |potential IMPROVEMENT          |
|ftsb-10K-multivalue-numeric-json                                | 844 +- 0.9%  (7 datapoints)            | 831 +- nan%  (1 datapoints)                       |-1.5%                   |-- no change --                |
|ftsb-10K-singlevalue-numeric-json                               | 361 +- 0.9%  (7 datapoints)            | 369 +- nan%  (1 datapoints)                       |2.0%                    |-- no change --                |
|ftsb-1K-enwiki_abstract-hashes-term-contains                    | 1602 +- 0.7%  (7 datapoints)           | 1602 +- nan%  (1 datapoints)                      |0.0%                    |-- no change --                |
|ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query| 351 +- 7.8%  (7 datapoints)            | 351 +- nan%  (1 datapoints)                       |0.0%                    |waterline=7.8%. -- no change --|
|ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query       | 2640 +- 5.8%  (7 datapoints)           | 2574 +- nan%  (1 datapoints)                      |-2.5%                   |waterline=5.8%. -- no change --|
|ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query      | 996 +- 7.8%  (7 datapoints)            | 1014 +- nan%  (1 datapoints)                      |1.8%                    |waterline=7.8%. -- no change --|
|ftsb-1M-enwiki_abstract-hashes-load                             | 22955 +- 2.7%  (7 datapoints)          | 21227 +- nan%  (1 datapoints)                     |-7.5%                   |REGRESSION                     |
|ftsb-1M-nyc_taxis-ftadd-load                                    | 21082 +- 1.5%  (7 datapoints)          | 19257 +- nan%  (1 datapoints)                     |-8.7%                   |REGRESSION                     |
|ftsb-1M-nyc_taxis-hashes-load                                   | 22250 +- 1.3%  (7 datapoints)          | 20890 +- nan%  (1 datapoints)                     |-6.1%                   |REGRESSION                     |
|search-ftsb-10K-enwiki_abstract-hashes-term-withoutsuffix-trie  | 36205 +- 1.5%  (7 datapoints)          | 35410 +- nan%  (1 datapoints)                     |-2.2%                   |-- no change --                |
|search-ftsb-10K-enwiki_abstract-hashes-term-withsuffix-trie     | 35446 +- 1.2%  (7 datapoints)          | 36227 +- nan%  (1 datapoints)                     |2.2%                    |-- no change --                |
|search-geo                                                      | 207 +- 2.4%  (7 datapoints)            | 201 +- nan%  (1 datapoints)                       |-3.0%                   |-- no change --                |
|search-numeric                                                  | 2994 +- 9.5%  (7 datapoints)           | 3027 +- nan%  (1 datapoints)                      |1.1%                    |waterline=9.5%. -- no change --|
|search-numeric-sortby                                           | 3512 +- 32.9% UNSTABLE (7 datapoints)  | 3043 +- nan%  (1 datapoints)                      |-13.4%                  |UNSTABLE (very high variance)  |
|search-numeric-sortby-desc                                      | 3241 +- 24.4% UNSTABLE (7 datapoints)  | 2812 +- nan%  (1 datapoints)                      |-13.2%                  |UNSTABLE (very high variance)  |

**Comment by filipecosta90** [comment]
### Automated performance analysis summary

This comment was automatically generated given there is performance data available.

In summary:
- Detected a total of 14 stable tests between versions.
- Detected a total of 2 highly unstable benchmarks.
- Detected a total of 3 regressions bellow the regression water line 5.0.

You can check a comparison in detail via the [grafana link](https://benchmarksrediscom.grafana.net/d//3Ejv2wZnk/?var-branch=master&var-branch=first_rust_code)

### Comparison between master and first_rust_code.

Time Period from 30 days ago. (environment used: oss-standalone)

|                           Test Case                            |Baseline master (median obs. +- std.dev)|Comparison first_rust_code (median obs. +- std.dev)|% change (higher-better)|             Note              |
|----------------------------------------------------------------|----------------------------------------|---------------------------------------------------|------------------------|-------------------------------|
|ftsb-10K-enwiki_abstract-hashes-term-prefix                     | 7739 +- 3.4%  (7 datapoints)           | 7766 +- nan%  (1 datapoints)                      |0.3%                    |-- no change --                |
|ftsb-10K-enwiki_abstract-hashes-term-suffix                     | 1847 +- 0.5%  (7 datapoints)           | 1848 +- nan%  (1 datapoints)                      |0.0%                    |-- no change --                |
|ftsb-10K-enwiki_abstract-hashes-term-suffix-withsuffixtrie      | 80954 +- 5.2%  (7 datapoints)          | 82201 +- nan%  (1 datapoints)                     |1.5%                    |waterline=5.2%. -- no change --|
|ftsb-10K-enwiki_abstract-hashes-term-wildcard                   | 12795 +- 4.2%  (7 datapoints)          | 13272 +- nan%  (1 datapoints)                     |3.7%                    |potential IMPROVEMENT          |
|ftsb-10K-multivalue-numeric-json                                | 844 +- 0.9%  (7 datapoints)            | 831 +- nan%  (1 datapoints)                       |-1.5%                   |-- no change --                |
|ftsb-10K-singlevalue-numeric-json                               | 361 +- 0.9%  (7 datapoints)            | 369 +- nan%  (1 datapoints)                       |2.0%                    |-- no change --                |
|ftsb-1K-enwiki_abstract-hashes-term-contains                    | 1602 +- 0.7%  (7 datapoints)           | 1602 +- nan%  (1 datapoints)                      |0.0%                    |-- no change --                |
|ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query| 351 +- 7.8%  (7 datapoints)            | 351 +- nan%  (1 datapoints)                       |0.0%                    |waterline=7.8%. -- no change --|
|ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query       | 2640 +- 5.8%  (7 datapoints)           | 2574 +- nan%  (1 datapoints)                      |-2.5%                   |waterline=5.8%. -- no change --|
|ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query      | 996 +- 7.8%  (7 datapoints)            | 1014 +- nan%  (1 datapoints)                      |1.8%                    |waterline=7.8%. -- no change --|
|ftsb-1M-enwiki_abstract-hashes-load                             | 22955 +- 2.7%  (7 datapoints)          | 21227 +- nan%  (1 datapoints)                     |-7.5%                   |REGRESSION                     |
|ftsb-1M-nyc_taxis-ftadd-load                                    | 21082 +- 1.5%  (7 datapoints)          | 19257 +- nan%  (1 datapoints)                     |-8.7%                   |REGRESSION                     |
|ftsb-1M-nyc_taxis-hashes-load                                   | 22250 +- 1.3%  (7 datapoints)          | 20890 +- nan%  (1 datapoints)                     |-6.1%                   |REGRESSION                     |
|search-ftsb-10K-enwiki_abstract-hashes-term-withoutsuffix-trie  | 36205 +- 1.5%  (7 datapoints)          | 35410 +- nan%  (1 datapoints)                     |-2.2%                   |-- no change --                |
|search-ftsb-10K-enwiki_abstract-hashes-term-withsuffix-trie     | 35446 +- 1.2%  (7 datapoints)          | 36227 +- nan%  (1 datapoints)                     |2.2%                    |-- no change --                |
|search-geo                                                      | 207 +- 2.4%  (7 datapoints)            | 201 +- nan%  (1 datapoints)                       |-3.0%                   |-- no change --                |
|search-numeric                                                  | 2994 +- 9.5%  (7 datapoints)           | 3027 +- nan%  (1 datapoints)                      |1.1%                    |waterline=9.5%. -- no change --|
|search-numeric-sortby                                           | 3512 +- 32.9% UNSTABLE (7 datapoints)  | 3043 +- nan%  (1 datapoints)                      |-13.4%                  |UNSTABLE (very high variance)  |
|search-numeric-sortby-desc                                      | 3241 +- 24.4% UNSTABLE (7 datapoints)  | 2812 +- nan%  (1 datapoints)                      |-13.2%                  |UNSTABLE (very high variance)  |

**Comment by ashtul** [comment]
@filipecosta90 @MeirShpilraien The regressions are on the ingest commands where the trie is heavily used.
Most other benchmarks don't use the trie extensively.

**Comment by MeirShpilraien** [comment]
@ashtul yes I saw the small regression, will see how we can improve it without doing some hacky stuff..

**Comment by MeirShpilraien** [comment]
@oshadmi @rafie I believe the PR is in its final stages and can already be reviewed. Tests passes and benchmark seems ok.

@rafie please advice on the best approach to add it to the build system (including running `cargo test`). Also please advice how to correctly run the sanitiser (current the sanitiser CI failed because the rust code is not compile with sanitiser).

Thanks @filipecosta90 your benchmark system is **amazing**.
One comment about the benchmark, we have a lot of unstable benchmark tests with high variance, we should try to understand why this is the case and either fix it and maybe remove it?

**Pull request closed without merging**
