### PR TITLE
allow numeric query if a single value

### LINKED ISSUE #1620: Allow querying for exact matches on numeric fields without a range
Developer experience would be better if we could search for exact matches on a numeric field without using a range. In other words, this query should work -- `registered_on` being a NUMERIC field:

```
127.0.0.1:6379> ft.search user-idx "@registered_on:1601510400"
```

But it doesn't, currently. It requires a range:

```
127.0.0.1:6379> ft.search user-idx "@registered_on:[1601510400 1601510400]"
1) (integer) 2
2) "users:user:1"
3) 1) "first_name"
   2) "Andrew"
   3) "last_name"
   4) "B."
   5) "registered_on"
   6) "1601510400"
4) "users:user:2"
5) 1) "first_name"
   2) "Justin"
   3) "last_name"
   4) "C."
   5) "registered_on"
   6) "1601510400"
```

### PR DESCRIPTION
**Pull request by ashtul**
fix #1620

### CODE REVIEW

**Comment by abrookins** [comment]
This doesn’t seem quite right to me. Why would you have to use range syntax to match a single numeric value? The syntax should be discoverable and consistent, with the same syntax that works for finding specific text properties also working for numeric properties. Or am I missing something?

**Comment by ashtul** [comment]
@abrookins, tag fields require `{}`, and geo fields are also inside `[]`. Currently, our parsing method requires it to signal we are not dealing with a textual term.

**Comment by abrookins** [comment]
Ah, ok, I understood [] to mean a range but here it sounds like we need brackets to distinguish the input type.

**Review by rafie — APPROVED** [review]

**Comment by abrookins** [comment]
It sounds like this is a bigger question than this PR, but don’t we already know the type of data in the field? I.e. we know that the field is numeric, geo, tag - so why require people to specify that in queries?

**Comment by ashtul** [comment]
@abrookins 
In theory, you are correct. We could have known the type from the field. Currently, the way the parser is implemented, it must we check the type during the initial parsing.
We are in the process of shaking the numeric implementation. Therefore, I'm closing this PR for now until those changes are implemented.

**Comment by garygreen** [comment]
@ashtul 

> Currently, the way the parser is implemented, it must we check the type during the initial parsing.

Interesting, is that why tags has a different syntax as compared to all the other filters which use `[]` ?

**Current**: @cities:{ New York | Los Angeles | Barcelona }
**More Consistent**: @cities:[ New York | Los Angeles | Barcelona ]

RedisSearch knows what type the cities field is so would know the parameters passed is a series of tags. If `|` character needs to be searched then it can be escaped? Syntax for tags seems like the odd one out.

Also it's a bit confusing one of the examples in the docs is `@category:(articles|biographies)` - I would of assumed this should be `@category:[articles|biographies]` for consistency?

Seems like there is quite a lot of oddities in the general syntax. Especially the rather confusing number filtering with `-inf (` #1621

**Pull request closed without merging**
