### PR TITLE
[2.0] Cherry-pick issue 1827. Stopword to lower case

### PR DESCRIPTION
**Pull request by ashtul**
* test

* convert stopword to lower case

(cherry picked from commit e429355e61d342913706853a0e7620da04192e29)

### CODE REVIEW

**Comment by ashtul** [comment]
PR is awaiting a decision on which version it should be included in.

**Review by oshadmi — APPROVED** [review]
👍🏼 
BTW,
It already contains changes in [#1875](https://github.com/RediSearch/RediSearch/pull/1875)
Should it also be mentioned?

**Comment by rafie** [comment]
@ashtul @oshadmi This can break stuff in `2.0`. We previously considered cherry-picking this and decided to wait.
@emmanuelkeller WDYT?

**Comment by ashtul** [comment]
> @ashtul @oshadmi This can break stuff in `2.0`. We previously considered cherry-picking this and decided to wait.
> @emmanuelkeller WDYT?

The issue here is that a `stopword` with capital letters would be ignored on ingesting but at query time would be included in the query. In the test, we can see `boy With glasses` now return a result, whereas before the fix would return 0 results since it would look for `With` and not find it.
IMO, this is a bug, not a behavior change.

**Comment by ashtul** [comment]
Not cherrypicked due to breaking change

**Pull request closed without merging**
