### PR TITLE
Dictionary_Free does nothing on a non-NULL dict (#1870)

### PR DESCRIPTION
**Pull request by MeirShpilraien**

### CODE REVIEW

**Review by ashtul — APPROVED** [review]
Oh yes!

**Comment by ashtul** [comment]
Can we add a test?

**Comment by MeirShpilraien** [comment]
> Can we add a test?

https://github.com/RediSearch/RediSearch/pull/1861#issuecomment-784131139

**Comment by MeirShpilraien** [comment]
The real question is how our memory check did not fail when it was broken!!

**Pull request merged**
