### PR TITLE
DOC-2604: adding content for .../basic-constructs/query-constructs.md

### PR DESCRIPTION
**Pull request by dwdougherty**
**Describe the changes in the pull request**

A clear and concise description of what the PR is solving, including:
1. Adds content to currently empty docs page .../basic-constructs/query-constructs.md

**Which issues this PR fixes**
1. DOC-2604

**Main objects this PR modified**
1. /docs/docs/basic-constructs/query-constructs.md

**Mark if applicable**

- [ ] This PR introduces API changes
- [ ] This PR introduces serialization changes

### CODE REVIEW

**Comment by dwdougherty** [comment]
These docs aren't going to be added at this time, so I'm closing this PR.

**Comment by dwdougherty** [comment]
Re-opening.

**Comment by dwdougherty** [comment]
@adrianoamaral Please merge.

**Review by dmaier-redislabs — APPROVED** [review]

**Comment by dwdougherty** [comment]
Obsolete.

**Pull request closed without merging**
