### PR TITLE
Ignore sortable values which have RSValue_Null in rlookup (#919)

### PR DESCRIPTION
**Pull request by mnunberg**

### CODE REVIEW

**Comment by MeirShpilraien** [comment]
@mnunberg is this fixes any crash? cause I just check it on master and its not crashing:
```
127.0.0.1:6379> 'ft.create' 'idx' 'schema' 't1' 'text' 'sortable' 'n1' 'numeric' 'sortable'
OK
127.0.0.1:6379> 'ft.add' 'idx' 'doc1' 1 'fields' 'n1' 42
OK
127.0.0.1:6379> 'ft.search' 'idx' '*' 'sortby' 't1' 'desc'
1) (integer) 1
2) "doc1"
3) 1) "t1"
   2) (nil)
   3) "n1"
   4) "42"
```

**Comment by mnunberg** [comment]
It doesn't fix the crash, but 919 is about returning null values

**Comment by MeirShpilraien** [comment]
@mnunberg I am not sure its wrong to return a NULL value. After all its really a null value if its not set right?

**Comment by mnunberg** [comment]
It's not present in the document, and the user did not request it.

**Comment by MeirShpilraien** [comment]
Ft.search returns all the fields if not requested otherwise with RETURN. So it make sense to return all the fields even those who are not set (and is Null). Also I think this is how it behave on 1.4 and I do not want to change it.

**Comment by mnunberg** [comment]
@MeirShpilraien this field does not _exist_ at all.

**Comment by MeirShpilraien** [comment]
@mnunberg I am not follow, t1 is defined on the schema and just not set on ft.add, why you say its not exists?

**Comment by mnunberg** [comment]
We never return fields not present in the document, even in 1.4 - where we do a simple HGETALL. If the field is not in the document, it doesn't appear in HGETALL

**Pull request merged**
