### PR TITLE
Update coordination strategy of FlatSearchCommandHandler

### PR DESCRIPTION
**Pull request by Skoucail**
Add MRCluster_MastersOnly to the coordination strategy of the FlatSearchCommandHandler
Issue was posted in the deprecated repo RSCoordinator: https://github.com/RediSearch/RSCoordinator/issues/326
The comment in FlatSearchCommandHandler was already in place saying it should only query masters to avoid duplicates.
But the code didn't pass the MRCluster_MastersOnly flag.

### CODE REVIEW

**Comment by Skoucail** [comment]
@rafie 
Is this another dodgy test?
As i dont see why my change would introduce a memory leak

**Comment by rafie** [comment]
@Skoucail You're right, the memory leak comes from a unit test that has nothing to do with your changes. We're looking into it.

**Comment by Skoucail** [comment]
@rafie @ashtul 

First of all Happy new year!

Can someone review this change/issue and move it to master/2.2 branches?
We would love to start testing the 2.2 version of redisearch, but this issue where double results are returned by the coordinator really prevent us from upgrading.

**Comment by rafie** [comment]
@Skoucail Hello and happy new year!
We would love to move forward with the change, but currently face two problems:
1. The change exposes a problem that manifests itself in the form of an address sanitizer error. This problem is real, so we need to understand what exactly is going on there. It's probably not by the fix itself but by a neglected side effect.
2. We still cannot see the full impact of the change, not can we reproduce your original problem.

I suggest we start by tackling (2). Would it be possible for you to provide a simple reproduction of the erroneous behavior prior to the fix? That would be a great help!
Thank you.

**Comment by Skoucail** [comment]
@rafie 

**_Memory leak_**

Yea I believe the memory leak is present for a while already.
I already reported some kind of memory leak on 12/may/2020 (https://github.com/RediSearch/RSCoordinator/issues/262)
So I believe this shouldn't be blocking for this PR.

**_Reproducing the bug this PR fixes_**

Special for you I did a quick setup in docker.
The difficulty in testing this issue is that the master and slave nodes need to be on different IPs, so just running a cluster on 1 server with different port will execute other code in the coordinator => not triggering the bug. (Thats why I used docker and a bridge network)

So I will give all the commands I used (prerequisite: PC/Server with docker installed).
And will put the redis.config and the Dockerfile in attachment

**Create a docker network. So all containers get a IP and can communicate with each other**
`docker create network redis`

**Create the cluster (need to do that without the coordinator loaded, see issue https://github.com/RediSearch/RSCoordinator/issues/300)**

_I created a folder C:\temp\redis where i placed the file redis.config (see attachement). Replace path if you used other location._

```
docker run --name redis1 -d --network redis --restart=unless-stopped -v redis1_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config
docker run --name redis2 -d --network redis --restart=unless-stopped -v redis2_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config
docker run --name redis3 -d --network redis --restart=unless-stopped -v redis3_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config
docker run --name redis4 -d --network redis --restart=unless-stopped -v redis4_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config
docker run --name redis5 -d --network redis --restart=unless-stopped -v redis5_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config
docker run --name redis6 -d --network redis --restart=unless-stopped -v redis6_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config
```

_(check the IPs, they will differ in you deployment)_

`docker run -it --network redis --rm redis redis-cli --cluster create 172.20.0.2:6379 172.20.0.3:6379 172.20.0.4:6379 172.20.0.5:6379 172.20.0.6:6379 172.20.0.7:6379 --cluster-replicas 1`

Redeploy the cluster with coordinator module loaded

```
docker stop redis1
docker stop redis2
docker stop redis3
docker stop redis4
docker stop redis5
docker stop redis6

docker rm redis1
docker rm redis2
docker rm redis3
docker rm redis4
docker rm redis5
docker rm redis6

docker run --name redis1 -d --network redis --restart=unless-stopped -v redis1_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config --loadmodule /usr/lib/redis/modules/module-oss.so PARTIAL_INDEXED_DOCS 1
docker run --name redis2 -d --network redis --restart=unless-stopped -v redis2_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config --loadmodule /usr/lib/redis/modules/module-oss.so PARTIAL_INDEXED_DOCS 1
docker run --name redis3 -d --network redis --restart=unless-stopped -v redis3_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config --loadmodule /usr/lib/redis/modules/module-oss.so PARTIAL_INDEXED_DOCS 1
docker run --name redis4 -d --network redis --restart=unless-stopped -v redis4_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config --loadmodule /usr/lib/redis/modules/module-oss.so PARTIAL_INDEXED_DOCS 1
docker run --name redis5 -d --network redis --restart=unless-stopped -v redis5_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config --loadmodule /usr/lib/redis/modules/module-oss.so PARTIAL_INDEXED_DOCS 1
docker run --name redis6 -d --network redis --restart=unless-stopped -v redis6_data:/data -v C:\temp\redis:/usr/local/etc/redis skoucail/redis-rscoordinator:6.2.6 redis-server /usr/local/etc/redis/redis.config --loadmodule /usr/lib/redis/modules/module-oss.so PARTIAL_INDEXED_DOCS 1
```

Now we have a 6 node (3 master, 3 slave) cluster up and running. With the coordinator module loaded.

**Deploy RedisInsight (optional)**

For easy testing I use RedisInsight. So I also deploy that.
`docker run --name redisinsightCluster --network redis --restart=unless-stopped -d -p 8001:8001 -v redisinsightCluster:/db redislabs/redisinsight:latest`

**Insert index + data***
```
FT.CREATE testIndex ON HASH PREFIX 1 key:keyid SCHEMA field1 TAG SORTABLE
HSET key:keyid:1 field1:value1
```

**Run FT.SEARCH**
`FT.SEARCH testIndex *`

**The result = bugged**
image

**The dockerfile**
If you wondering, the dockerfile does nothing special. It takes the official redis image (redis version 6.2.6)
Pulls and builds the coordinator module (from this repo, branch 2.2)
```
RUN git config --global url."https://github.com/".insteadOf git@github.com:; \
    git config --global url."https://".insteadOf git://; \
    git clone -b 2.2 --recurse-submodules  https://github.com/RediSearch/RediSearch.git /RediSearch; \    
    cd /RediSearch; \    
    make build COORD=oss;

**Comment by MeirShpilraien** [comment]
@Skoucail how do you explain you did not encounter this problem on older version?

**Comment by Skoucail** [comment]
> @Skoucail how do you explain you did not encounter this problem on older version?

@MeirShpilraien
I can't...
If you compare the code from the coordinator between 2.0 and 2.2 you can see it changed a lot.
I can guess 2 possibilities
1. The flow of executing queries changed from version 2.0 to 2.2 => not executing FlatSearchCommandHandler for this call.
2. Some post command processing cleaned the results removing the duplicates.

But my c++ knowledge is very limited (i'm a c# dev) so I have to do all my research on github as I have no c++ tools or develop environment...

I can just state the facts.
In version 2.0 we don't have this issue (we are running in production already)
I upgraded our alpha environment to 2.2 and start getting errors. After some digging I found out we got double results.

Some changes in ResiSearch 2.2 prevents a rollback so our alpha environment was stuck.
That was the reason why i started digging into the issue.

With the new FT.EXPLAIN function I found out that the coordinator in version 2.2 starts returning results from both the master and the slave node.

So I started digging in the code,
Thats when I found the comment `// we also ask only masters to serve the request, to avoid duplications by random` (line above the code I changed in this PR)
But the code didn't specify masters only. So I made a fork, changed the code, deployed to our alpha environment and all was back to normal.

And finally to save you guys some work I made a this PR.

**Comment by MeirShpilraien** [comment]
I am afraid we are missing some other regression and that this fix will only hide it. @rafie I believe this deserves a deeper investigation and should be prioritise higher.

**Comment by Skoucail** [comment]
> I am afraid we are missing some other regression and that this fix will only hide it. @rafie I believe this deserves a deeper investigation and should be prioritise higher.

Thanks in advance!
I know I'm an early adopter so I can expect some issues/kinks
But as you can see in my test setup, this is so a basic setup that the issue is quite impactful and blocking.
So plz keep me updated if an other fix gets checked in.

**Comment by ashtul** [comment]
> I am afraid we are missing some other regression and that this fix will only hide it. @rafie I believe this deserves a deeper investigation and should be prioritised higher.

@MeirShpilraien can this be related to the performance changes we have made to the coordinator?

**Review by ashtul — APPROVED** [review]
@Skoucail Thank you for this fix.
We made a thorough investigation to understand the root cause of this bug and concluded your suggestion is the right fix for the moment.
Cheers

**Comment by Skoucail** [comment]
@ashtul 
Your very welkom.
Thanks for investigating and approving my changes.
I hope they get merged and moved to the 2.2 branch very soon so I can test the newest version of RediSearch + coord.

**Review by rafie — APPROVED** [review]

**Pull request merged**
