### PR TITLE
Fix fuzzy scoring+hl

### LINKED ISSUE #1117: Fuzzy search considers only a single field for score
```
FT.CREATE jobs SCHEMA job_title TEXT WEIGHT 100 job_title_normalized TEXT WEIGHT 10 description TEXT
```

```
> FT.SEARCH jobs %Administrator% WITHSCORES HIGHLIGHT
 1) (integer) 3
 2) "2"
 3) "0.10000000000000001"
 4) 1) "job_title"
    2) "Ginobli2"
    3) "job_title_normalized"
    4) "<b>administrator</b>"
    5) "description"
    6) "xyz"
 5) "1"
 6) "0.10000000000000001"
 7) 1) "job_title"
    2) "Administrator1"
    3) "job_title_normalized"
    4) "<b>administrator</b>"
    5) "description"
    6) "dsfh"
 8) "3"
 9) "0.040000000000000001"
10) 1) "job_title"
    2) "pop"
    3) "job_title_normalized"
    4) "parker"
    5) "description"
    6) "<b>administrator</b> <b>administrator</b> <b>administrator</b> <b>administrator</b>"
```

### PR DESCRIPTION
**Pull request by ashtul**
fix #1117 
Set quickExit flag to 0 in order to get all fuzzy options

### CODE REVIEW

**Comment by ashtul** [comment]
There is a small behavior change as can be seen on summerize test

**Comment by MeirShpilraien** [comment]
@mnunberg I was going to write exactly that, we should consider the performance implications of this change and whether or not we want to give it as a configuration argument maybe? I do not mind merging it to master but not cherry-pick it to 1.6 right now until we will be more sure whether or not there is a performance issue here. I just do not want regression with performance issues on 1.6.

**Comment by ashtul** [comment]
@mnunberg @MeirShpilraien 
Can we change `quickExit` only for fuzzy search in `getIndexResult()` before we call SkipTo()?

**Comment by ashtul** [comment]
Not the right solution...

**Pull request closed without merging**
