### PR TITLE
Change fields name to be case sensitive

### PR DESCRIPTION
**Pull request by MeirShpilraien**

### CODE REVIEW

**Comment by rafie** [comment]
@MeirShpilraien 
There are several `strcasecmp`-s I'm not sure about:
```
RediSearch\src\sortable.c
     205      if (!strcasecmp(tbl->fields[i].name, field)) {
RediSearch\src\stemmer.c
      70      if (!strcasecmp(language, __langPairs[i].str)) {
RediSearch\src\aggregate\aggregate_exec.c
     126        if (rule && ((rule->lang_field && strcasecmp(kk->name, rule->lang_field) == 0) ||
     127            (rule->score_field && strcasecmp(kk->name, rule->score_field) == 0))) {
RediSearch\src\aggregate\aggregate_request.c
      60      if (!strcasecmp(fields->fields[ii].name, name)) {
RediSearch\src\aggregate\reducer.c
      25      if (!strcasecmp(globalRegistry[ii].name, name)) {
```

**Comment by MeirShpilraien** [comment]
@rafie :
```
RediSearch\src\sortable.c - dead code
     205      if (!strcasecmp(tbl->fields[i].name, field)) {
RediSearch\src\stemmer.c - this is the language for the stemmer and not a field name
      70      if (!strcasecmp(language, __langPairs[i].str)) {
RediSearch\src\aggregate\aggregate_exec.c - fixes and tested
     126        if (rule && ((rule->lang_field && strcasecmp(kk->name, rule->lang_field) == 0) ||
     127            (rule->score_field && strcasecmp(kk->name, rule->score_field) == 0))) {
RediSearch\src\aggregate\aggregate_request.c - still checking
      60      if (!strcasecmp(fields->fields[ii].name, name)) {
RediSearch\src\aggregate\reducer.c - this is the groups names and not the actual fields names
      25      if (!strcasecmp(globalRegistry[ii].name, name)) {
```

**Comment by MeirShpilraien** [comment]
- [ ] fix tests to pass on coordinator

**Comment by MeirShpilraien** [comment]
@rafie fix this one also:
```
RediSearch\src\aggregate\aggregate_request.c
      60      if (!strcasecmp(fields->fields[ii].name, name)) {
```

**Comment by MeirShpilraien** [comment]
@ashtul do you see anything I missed?

**Comment by ashtul** [comment]
related to #1355

**Pull request merged**
