### PR TITLE
see #782, added the ability to free document from llapi

### PR DESCRIPTION
**Pull request by MeirShpilraien**

### CODE REVIEW

**Comment by mnunberg** [comment]
I'm working on the document API; so let's add this functionality after the other thing is merged.

**Comment by MeirShpilraien** [comment]
@mnunberg can I rebase and merge?

**Comment by MeirShpilraien** [comment]
@mnunberg 
The ownership is very clear. as long as it did not pass to us via the addDocument the owner is the one created the document and he should free it. Once it pass to us we are the owners and we should free it.

**Comment by mnunberg** [comment]
Ahh, I see. @swilly22 asked for the change to only free the document if it wasn't added yet. I guess this means that we keep the semantics of AddDocument retaining "ownership" of the document. In which case, I think it's good as-is

**Comment by MeirShpilraien** [comment]
@mnunberg I rebased, can you approve?

**Pull request merged**
