### PR TITLE
added ft._list command

### PR DESCRIPTION
**Pull request by MeirShpilraien**

### CODE REVIEW

**Comment by ashtul** [comment]
fix #1119

**Comment by MeirShpilraien** [comment]
@ashtul I would not say that it fix it, it's not efficient on large amount of indexes, we decided that it will be an internal command for now until we will define a unified scan API for all modules.

**Comment by K-Jo** [comment]
@gkorland @MeirShpilraien @ashtul this PR is missing documentation

**Comment by gkorland** [comment]
@K-Jo wasn't that the perhaps of calling it `FT._LIST` and not official public `FT.LIST`?

**Comment by MeirShpilraien** [comment]
Its FT._LIST and its not missing documentation, we decided its going to be an internal command and so not to document it.

**Pull request merged**
